[profile.default]
solc_version = "0.8.28"
evm_version = "paris"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "../" }]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
